const { onRequest } = require('firebase-functions/v2/https');
const { defineSecret } = require('firebase-functions/params');
const { setGlobalOptions } = require('firebase-functions/v2');
setGlobalOptions({ region: 'us-central1', maxInstances: 10 });
const OPENAI_API_KEY = defineSecret('OPENAI_API_KEY');
const SYSTEM = `You are an expert fantasy football GM for a competitive 14-team half-PPR league. Use only supplied data and distinguish measured inputs from inference. Never invent injuries, news, odds, projections, players, schedules or facts. For draft analysis recommend one best pick plus two alternatives using roster construction, scarcity, ECR, ADP and projections. For weekly analysis prioritize the actual NFL opponent for each player, matchup-adjusted projections and simulated fantasy win probability. Explain whether the manager should prefer floor or ceiling based on win probability. Identify start/sit priorities, exploitable roster mismatches and realistic trades using all league rosters. Clearly separate one-week matchup value from rest-of-season value. If a data field is absent, explicitly say it is unavailable rather than guessing.`;
function taskPrompt(task){return task==='draft'?'Analyze the current draft state and recommend the best selection now.':'Act as the AI Fantasy GM. Analyze this exact NFL week, the fantasy opponent, adjusted projections, simulation and league rosters. Give the highest-impact actions first.'}
function extractText(data){if(typeof data.output_text==='string')return data.output_text.trim();return(data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text||'').join('\n').trim()}
exports.aiAdvice=onRequest({secrets:[OPENAI_API_KEY],timeoutSeconds:60,memory:'256MiB'},async(req,res)=>{res.set('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const{task,context}=req.body||{};if(!['draft','weekly'].includes(task)||!context||typeof context!=='object')return res.status(400).json({error:'Invalid request'});const serialized=JSON.stringify(context);if(serialized.length>220000)return res.status(413).json({error:'Analysis context too large'});try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY.value()}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6',instructions:SYSTEM,input:`${taskPrompt(task)}\n\nLEAGUE DATA:\n${serialized}`,max_output_tokens:1600})});const data=await response.json();if(!response.ok){console.error('OpenAI error',response.status,data?.error?.message||'unknown');return res.status(response.status>=500?502:response.status).json({error:data?.error?.message||'AI request failed'})}const advice=extractText(data);if(!advice)return res.status(502).json({error:'AI returned no advice'});return res.status(200).json({advice})}catch(error){console.error('aiAdvice failure',error);return res.status(500).json({error:'AI analysis temporarily unavailable'})}});
exports.nflWeek=onRequest({timeoutSeconds:30,memory:'256MiB'},async(req,res)=>{res.set('Cache-Control','public, max-age=1800');const week=Math.max(1,Math.min(18,Number(req.query.week)||1));const season=Number(req.query.season)||new Date().getFullYear();try{const url=`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?dates=${season}&seasontype=2&week=${week}`;const r=await fetch(url,{headers:{'User-Agent':'FantasyManager/1.0'}});if(!r.ok)throw new Error(`Schedule provider ${r.status}`);const data=await r.json();const games=(data.events||[]).map(e=>{const c=e.competitions?.[0],teams=c?.competitors||[],home=teams.find(t=>t.homeAway==='home'),away=teams.find(t=>t.homeAway==='away');return{id:e.id,date:e.date||'',home:home?.team?.abbreviation||'',away:away?.team?.abbreviation||'',status:e.status?.type?.description||'',completed:!!e.status?.type?.completed}}).filter(g=>g.home&&g.away);return res.status(200).json({season,week,source:'ESPN public NFL scoreboard',fetchedAt:new Date().toISOString(),games})}catch(error){console.error('nflWeek failure',error);return res.status(502).json({error:'NFL schedule temporarily unavailable'})}});
