const SLEEPER_API='https://api.sleeper.app/v1';
function ensureAutoData(){if(!state.autoLeague||typeof state.autoLeague!=='object')state.autoLeague={sleeperLeagueId:'',week:1,lastSync:'',projectionSource:'Sleeper matchup data'};if(!state.weeklyProjections||typeof state.weeklyProjections!=='object')state.weeklyProjections={}}
function playerBySleeperId(id){return state.players.find(p=>String(p.sleeperId||'')===String(id))}
async function sleeperJson(path){const r=await fetch(`${SLEEPER_API}${path}`);if(!r.ok)throw new Error(`Sleeper API request failed (${r.status})`);return r.json()}
async function syncSleeperLeague(){ensureAutoData();const leagueId=document.getElementById('sleeper-league-id')?.value.trim()||state.autoLeague.sleeperLeagueId;if(!leagueId)return toast('Enter a Sleeper league ID','error');const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||state.autoLeague.week||1));const btn=document.getElementById('sync-league-data');if(btn)btn.disabled=true;try{await refreshSleeperMetadata({force:true,silent:true});const [league,rosters,users,matchups]=await Promise.all([sleeperJson(`/league/${leagueId}`),sleeperJson(`/league/${leagueId}/rosters`),sleeperJson(`/league/${leagueId}/users`),sleeperJson(`/league/${leagueId}/matchups/${week}`)]);const userNames=new Map(users.map(u=>[String(u.user_id),u.metadata?.team_name||u.display_name||`Team ${u.user_id}`]));const rosterById=new Map(rosters.map(r=>[Number(r.roster_id),r]));ensureLeagueData();rosters.forEach(r=>{const slot=Number(r.roster_id);if(slot>=1&&slot<=state.leagueTeams.length){const t=state.leagueTeams.find(x=>x.slot===slot);if(t)t.name=userNames.get(String(r.owner_id))||t.name}state.teamRosters[String(slot)]=(r.players||[]).map(id=>playerBySleeperId(id)?.id).filter(Boolean)});const mySlot=Number(state.settings.draftSlot);const mine=matchups.find(m=>Number(m.roster_id)===mySlot);if(mine){const opp=matchups.find(m=>m.matchup_id===mine.matchup_id&&Number(m.roster_id)!==mySlot);if(opp)state.matchups[String(week)]=Number(opp.roster_id)}matchups.forEach(m=>{const ids=m.players||[],points=m.players_points||{};ids.forEach(id=>{const p=playerBySleeperId(id);if(!p)return;const actual=num(points[id]);if(!state.weeklyProjections[String(week)])state.weeklyProjections[String(week)]={};if(actual!==null)state.weeklyProjections[String(week)][p.id]=actual})});state.autoLeague={...state.autoLeague,sleeperLeagueId:leagueId,week,lastSync:new Date().toISOString(),leagueName:league.name||''};saveState();renderLeagueTeams();renderAutoSync();toast(`Synced ${league.name||'league'} · Week ${week}`)}catch(e){console.error(e);toast(e.message,'error')}finally{if(btn)btn.disabled=false}}
function weeklyPlayerValue(p){ensureAutoData();const week=String(Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||1))),v=num(state.weeklyProjections?.[week]?.[p.id]);return v!==null?v:playerWeeklyValue(p)}
function renderAutoSync(){ensureAutoData();const box=document.getElementById('auto-league-sync');if(!box)return;box.innerHTML=`<div class="surface-head no-pad"><div><span class="section-label">AUTOMATIC LEAGUE DATA</span><h2>Roster & weekly data sync</h2></div>${state.autoLeague.lastSync?`<span class="mini-pill">Synced ${esc(prettyDateTime(state.autoLeague.lastSync))}</span>`:''}</div><p class="helper">Connect a Sleeper league to automatically import every roster, team identity, the selected week's opponent and available matchup player scoring. Manual roster entry remains available as a fallback.</p><div class="auto-sync-controls"><label>Sleeper league ID<input id="sleeper-league-id" value="${esc(state.autoLeague.sleeperLeagueId||'')}" placeholder="e.g. 1234567890"></label><button class="btn primary" id="sync-league-data">Sync league & week</button></div>${state.autoLeague.leagueName?`<p class="helper"><strong>${esc(state.autoLeague.leagueName)}</strong> · Week ${state.autoLeague.week}</p>`:''}`;document.getElementById('sync-league-data')?.addEventListener('click',syncSleeperLeague)}
function installAutoUI(){ensureAutoData();const leagueView=document.getElementById('view-league');if(!leagueView||document.getElementById('auto-league-sync'))return;const first=leagueView.querySelector('.surface');first?.insertAdjacentHTML('beforebegin','<article class="surface form-surface"><div id="auto-league-sync"></div></article>');const style=document.createElement('style');style.textContent='.auto-sync-controls{display:grid;grid-template-columns:minmax(240px,1fr) auto;gap:12px;align-items:end;margin-top:14px}@media(max-width:700px){.auto-sync-controls{grid-template-columns:1fr}}';document.head.appendChild(style);renderAutoSync()}
installAutoUI();
const autoBasePlayerWeeklyValue=playerWeeklyValue;playerWeeklyValue=function(p){ensureAutoData();const week=String(Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||1))),v=num(state.weeklyProjections?.[week]?.[p.id]);return v!==null?v:autoBasePlayerWeeklyValue(p)};
