function ensureAdviceData(){if(!state.teamRosters||typeof state.teamRosters!=='object')state.teamRosters={};if(!state.tradeTargets||!Array.isArray(state.tradeTargets))state.tradeTargets=[]}
function rosterForSlot(slot){ensureAdviceData();if(Number(slot)===Number(state.settings.draftSlot))return myRoster();return (state.teamRosters[String(slot)]||[]).map(getPlayer).filter(Boolean)}
function playerWeeklyValue(p){const proj=num(p.projection);if(proj!==null)return proj;const rank=num(p.rank,250),adp=num(p.adp,rank);return Math.max(1,28-(rank*.09)-(adp*.025))}
function rosterStrength(players){return players.reduce((sum,p)=>sum+playerWeeklyValue(p),0)}
function positionalCounts(players){const out={QB:0,RB:0,WR:0,TE:0,'D/ST':0,K:0};players.forEach(p=>{const pos=primaryPos(p);if(out[pos]!==undefined)out[pos]++});return out}
function needPositions(players){const c=positionalCounts(players),r=state.settings.roster,needs=[];[['QB','QB'],['RB','RB'],['WR','WR'],['TE','TE']].forEach(([p,k])=>{if(c[p]<Number(r[k]||0))needs.push(p)});return needs}
function matchupAnalysis(week){const opponent=Number(state.matchups?.[String(week)]||0),mine=myRoster(),theirs=opponent?rosterForSlot(opponent):[],myScore=rosterStrength(mine),theirScore=rosterStrength(theirs),delta=myScore-theirScore;return{opponent,mine,theirs,myScore,theirScore,delta,edge:!theirs.length?'unknown':delta>5?'favored':delta<-5?'underdog':'close'}}
function tradeCandidates(opponentSlot){const mine=myRoster(),theirs=rosterForSlot(opponentSlot),myNeeds=needPositions(mine),theirNeeds=needPositions(theirs);return theirs.map(target=>{let score=playerWeeklyValue(target)*2;if(myNeeds.includes(primaryPos(target)))score+=18;const give=mine.filter(p=>theirNeeds.includes(primaryPos(p))).sort((a,b)=>playerWeeklyValue(b)-playerWeeklyValue(a))[0]||mine.slice().sort((a,b)=>playerWeeklyValue(a)-playerWeeklyValue(b))[0];if(give)score-=Math.max(0,playerWeeklyValue(give)-playerWeeklyValue(target));return{target,give,score}}).sort((a,b)=>b.score-a.score).slice(0,6)}
function renderAdvice(){ensureAdviceData();const root=document.getElementById('advice-engine');if(!root)return;const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||1)),a=matchupAnalysis(week);if(!a.opponent){root.innerHTML='<div class="empty-state compact">Save a weekly opponent above to generate matchup and trade advice.</div>';return}const opponentName=leagueTeamName(a.opponent),needs=needPositions(a.mine),targets=tradeCandidates(a.opponent);const matchupText=!a.theirs.length?'Add the opponent roster below for a head-to-head projection.':a.edge==='favored'?`Projected edge: +${a.delta.toFixed(1)} points.`:a.edge==='underdog'?`Projected deficit: ${a.delta.toFixed(1)} points. Prioritize ceiling and upgrades.`:`Projected within ${Math.abs(a.delta).toFixed(1)} points — treat this as a close matchup.`;root.innerHTML=`<div class="advice-grid"><div class="advice-card"><span>MATCHUP READ</span><h3>${esc(state.settings.teamName)} vs ${esc(opponentName)}</h3><p>${matchupText}</p><div class="advice-metrics"><b>${a.myScore.toFixed(1)}<small>Your value</small></b><b>${a.theirScore.toFixed(1)}<small>Opponent</small></b></div><p>${needs.length?`Roster priorities: ${needs.join(', ')}.`:'Core starting positions are covered; target upside and depth.'}</p></div><div class="advice-card"><span>TRADE IDEAS</span><h3>Targets on ${esc(opponentName)}</h3>${targets.length?targets.map(x=>`<div class="trade-row"><div><strong>${esc(x.target.name)}</strong><small>${esc(primaryPos(x.target))} · value ${playerWeeklyValue(x.target).toFixed(1)}</small></div><div>${x.give?`Explore offering <b>${esc(x.give.name)}</b>`:'Potential target'}</div></div>`).join(''):'<p>Add the opponent roster to generate trade targets.</p>'}</div></div>`}
function renderOpponentRosterEditor(){const box=document.getElementById('opponent-roster-editor');if(!box)return;const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||1)),slot=Number(state.matchups?.[String(week)]||0);if(!slot){box.innerHTML='';return}const roster=new Set(state.teamRosters?.[String(slot)]||[]),options=state.players.filter(p=>!isMine(p.id)).sort((a,b)=>num(a.rank,9999)-num(b.rank,9999)).slice(0,350);box.innerHTML=`<div class="surface-head no-pad"><div><span class="section-label">OPPONENT ROSTER</span><h2>${esc(leagueTeamName(slot))}</h2></div><span class="mini-pill">${roster.size} players</span></div><p class="helper">Select known players on this opponent. This powers projected matchup strength and trade-fit analysis.</p><div class="opponent-roster-list">${options.map(p=>`<label><input type="checkbox" data-opponent-player="${p.id}" ${roster.has(p.id)?'checked':''}><span>${esc(p.name)} · ${esc(primaryPos(p))} · ${esc(p.team||'')}</span></label>`).join('')}</div>`}
function saveOpponentRosterFromUI(){const week=Number(document.getElementById('matchup-week')?.value)||1,slot=Number(state.matchups?.[String(week)]||0);if(!slot)return;state.teamRosters[String(slot)]=[...document.querySelectorAll('[data-opponent-player]:checked')].map(x=>x.dataset.opponentPlayer);saveState();renderAdvice();renderOpponentRosterEditor()}
function installAdviceUI(){const matchupSurface=document.querySelector('#view-league .matchup-surface');if(!matchupSurface||document.getElementById('advice-engine'))return;matchupSurface.insertAdjacentHTML('afterend',`<article class="surface form-surface"><div class="surface-head no-pad"><div><span class="section-label">WEEKLY ENGINE</span><h2>Matchup & trade advice</h2></div></div><div id="advice-engine"></div></article><article class="surface form-surface"><div id="opponent-roster-editor"></div><div class="form-actions"><button class="btn primary" type="button" id="save-opponent-roster">Save opponent roster</button></div></article>`);const style=document.createElement('style');style.textContent=`.advice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.advice-card{border:1px solid var(--border,#d9dee8);border-radius:14px;padding:16px}.advice-card>span{font-size:11px;font-weight:800;letter-spacing:.08em}.advice-card h3{margin:6px 0 8px}.advice-metrics{display:flex;gap:10px;margin:14px 0}.advice-metrics b{font-size:22px}.advice-metrics small{display:block;font-size:10px;font-weight:500}.trade-row{display:flex;justify-content:space-between;gap:12px;border-top:1px solid var(--border,#d9dee8);padding:9px 0}.trade-row small{display:block}.opponent-roster-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:7px;max-height:360px;overflow:auto;margin:12px 0}.opponent-roster-list label{display:flex;gap:8px;align-items:center;padding:7px;border:1px solid var(--border,#d9dee8);border-radius:9px}@media(max-width:800px){.advice-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);document.getElementById('save-opponent-roster')?.addEventListener('click',()=>{saveOpponentRosterFromUI();toast('Opponent roster saved')})}
installAdviceUI();renderOpponentRosterEditor();renderAdvice();
const adviceBaseRenderLeagueTeams=renderLeagueTeams;renderLeagueTeams=function(){adviceBaseRenderLeagueTeams();renderOpponentRosterEditor();renderAdvice()};
