function ensureAdviceData(){if(!state.teamRosters||typeof state.teamRosters!=='object')state.teamRosters={};if(!state.tradeTargets||!Array.isArray(state.tradeTargets))state.tradeTargets=[];syncDraftRosters()}
function syncDraftRosters(){if(!state.teamRosters||typeof state.teamRosters!=='object')state.teamRosters={};for(let slot=1;slot<=Number(state.settings.teams||14);slot++){const key=String(slot),draftIds=state.picks.filter(p=>Number(p.teamSlot)===slot).map(p=>p.playerId);if(!Array.isArray(state.teamRosters[key]))state.teamRosters[key]=[];draftIds.forEach(id=>{if(!state.teamRosters[key].includes(id))state.teamRosters[key].push(id)})}}
function rosterIdsForSlot(slot){ensureAdviceData();const key=String(slot);if(Number(slot)===Number(state.settings.draftSlot)){const mine=[...myRoster().map(p=>p.id),...(state.teamRosters[key]||[])];return [...new Set(mine)]}return [...new Set(state.teamRosters[key]||[])]}
function rosterForSlot(slot){return rosterIdsForSlot(slot).map(getPlayer).filter(Boolean)}
function playerWeeklyValue(p){const proj=num(p.projection);if(proj!==null)return proj;const rank=num(p.rank,250),adp=num(p.adp,rank);return Math.max(1,28-(rank*.09)-(adp*.025))}
function rosterStrength(players){return players.reduce((sum,p)=>sum+playerWeeklyValue(p),0)}
function positionalCounts(players){const out={QB:0,RB:0,WR:0,TE:0,'D/ST':0,K:0};players.forEach(p=>{const pos=primaryPos(p);if(out[pos]!==undefined)out[pos]++});return out}
function needPositions(players){const c=positionalCounts(players),r=state.settings.roster,needs=[];[['QB','QB'],['RB','RB'],['WR','WR'],['TE','TE']].forEach(([p,k])=>{if(c[p]<Number(r[k]||0))needs.push(p)});return needs}
function matchupAnalysis(week){const opponent=Number(state.matchups?.[String(week)]||0),mine=rosterForSlot(state.settings.draftSlot),theirs=opponent?rosterForSlot(opponent):[],myScore=rosterStrength(mine),theirScore=rosterStrength(theirs),delta=myScore-theirScore;return{opponent,mine,theirs,myScore,theirScore,delta,edge:!theirs.length?'unknown':delta>5?'favored':delta<-5?'underdog':'close'}}
function tradeCandidates(opponentSlot){const mine=rosterForSlot(state.settings.draftSlot),theirs=rosterForSlot(opponentSlot),myNeeds=needPositions(mine),theirNeeds=needPositions(theirs);return theirs.map(target=>{let score=playerWeeklyValue(target)*2;if(myNeeds.includes(primaryPos(target)))score+=18;const give=mine.filter(p=>theirNeeds.includes(primaryPos(p))).sort((a,b)=>playerWeeklyValue(b)-playerWeeklyValue(a))[0]||mine.slice().sort((a,b)=>playerWeeklyValue(a)-playerWeeklyValue(b))[0];if(give)score-=Math.max(0,playerWeeklyValue(give)-playerWeeklyValue(target));return{target,give,score}}).sort((a,b)=>b.score-a.score).slice(0,6)}
function renderAdvice(){ensureAdviceData();const root=document.getElementById('advice-engine');if(!root)return;const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||1)),a=matchupAnalysis(week);if(!a.opponent){root.innerHTML='<div class="empty-state compact">Save a weekly opponent above to generate matchup and trade advice.</div>';return}const opponentName=leagueTeamName(a.opponent),needs=needPositions(a.mine),targets=tradeCandidates(a.opponent);const matchupText=!a.theirs.length?'Add the opponent roster below for a head-to-head projection.':a.edge==='favored'?`Projected edge: +${a.delta.toFixed(1)} points.`:a.edge==='underdog'?`Projected deficit: ${a.delta.toFixed(1)} points. Prioritize ceiling and upgrades.`:`Projected within ${Math.abs(a.delta).toFixed(1)} points — treat this as a close matchup.`;root.innerHTML=`<div class="advice-grid"><div class="advice-card"><span>MATCHUP READ</span><h3>${esc(state.settings.teamName)} vs ${esc(opponentName)}</h3><p>${matchupText}</p><div class="advice-metrics"><b>${a.myScore.toFixed(1)}<small>Your value</small></b><b>${a.theirScore.toFixed(1)}<small>Opponent</small></b></div><p>${needs.length?`Roster priorities: ${needs.join(', ')}.`:'Core starting positions are covered; target upside and depth.'}</p></div><div class="advice-card"><span>TRADE IDEAS</span><h3>Targets on ${esc(opponentName)}</h3>${targets.length?targets.map(x=>`<div class="trade-row"><div><strong>${esc(x.target.name)}</strong><small>${esc(primaryPos(x.target))} · value ${playerWeeklyValue(x.target).toFixed(1)}</small></div><div>${x.give?`Explore offering <b>${esc(x.give.name)}</b>`:'Potential target'}</div></div>`).join(''):'<p>No trade targets yet.</p>'}</div></div>`}
function rosterEditorMarkup(slot,label){const roster=new Set(rosterIdsForSlot(slot)),available=state.players.filter(p=>!roster.has(p.id)).sort((a,b)=>num(a.rank,9999)-num(b.rank,9999)).slice(0,500);const current=[...roster].map(getPlayer).filter(Boolean).sort((a,b)=>num(a.rank,9999)-num(b.rank,9999));return `<div class="weekly-roster-panel"><div class="surface-head no-pad"><div><span class="section-label">${esc(label)}</span><h2>${esc(leagueTeamName(slot))}</h2></div><span class="mini-pill">${current.length} players</span></div><div class="current-roster">${current.map(p=>`<div class="roster-edit-row"><span><strong>${esc(p.name)}</strong><small>${esc(primaryPos(p))} · ${esc(p.team||'')}</small></span><button class="btn secondary small" data-roster-remove="${p.id}" data-roster-slot="${slot}">Remove</button></div>`).join('')||'<div class="empty-state compact">No players on roster yet.</div>'}</div><div class="roster-add"><select data-roster-add-select="${slot}"><option value="">Add player…</option>${available.map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(primaryPos(p))} · ${esc(p.team||'')}</option>`).join('')}</select><button class="btn secondary small" data-roster-add="${slot}">Add</button></div></div>`}
function renderOpponentRosterEditor(){const box=document.getElementById('opponent-roster-editor');if(!box)return;const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||1)),opp=Number(state.matchups?.[String(week)]||0);if(!opp){box.innerHTML='<div class="empty-state compact">Select a weekly opponent to edit both rosters.</div>';return}syncDraftRosters();box.innerHTML=`<div class="weekly-rosters-head"><span class="section-label">CURRENT ROSTERS · WEEK ${week}</span><p class="helper">Draft selections are maintained automatically. Record waivers, drops and trades here; changes carry forward to future weeks.</p></div><div class="weekly-roster-grid">${rosterEditorMarkup(Number(state.settings.draftSlot),'MY ROSTER')}${rosterEditorMarkup(opp,'OPPONENT ROSTER')}</div>`;bindRosterEditorActions()}
function removeFromRoster(slot,id){const key=String(slot);state.teamRosters[key]=(state.teamRosters[key]||[]).filter(x=>x!==id);const pick=state.picks.find(p=>p.playerId===id&&Number(p.teamSlot)===Number(slot));if(pick)pick.rosterRemoved=true;if(Number(slot)===Number(state.settings.draftSlot))state.manualRosterIds=(state.manualRosterIds||[]).filter(x=>x!==id);saveState();renderOpponentRosterEditor();renderAdvice()}
function addToRoster(slot,id){if(!id)return;for(const key of Object.keys(state.teamRosters||{}))state.teamRosters[key]=(state.teamRosters[key]||[]).filter(x=>x!==id);const key=String(slot);state.teamRosters[key]=[...(state.teamRosters[key]||[]),id];if(Number(slot)===Number(state.settings.draftSlot)&&!state.manualRosterIds.includes(id))state.manualRosterIds.push(id);saveState();renderOpponentRosterEditor();renderAdvice()}
function bindRosterEditorActions(){document.querySelectorAll('[data-roster-remove]').forEach(b=>b.addEventListener('click',()=>removeFromRoster(Number(b.dataset.rosterSlot),b.dataset.rosterRemove)));document.querySelectorAll('[data-roster-add]').forEach(b=>b.addEventListener('click',()=>{const slot=Number(b.dataset.rosterAdd),sel=document.querySelector(`[data-roster-add-select="${slot}"]`);addToRoster(slot,sel?.value)}))}
function installAdviceUI(){const matchupSurface=document.querySelector('#view-league .matchup-surface');if(!matchupSurface||document.getElementById('advice-engine'))return;matchupSurface.insertAdjacentHTML('afterend',`<article class="surface form-surface"><div class="surface-head no-pad"><div><span class="section-label">WEEKLY ENGINE</span><h2>Matchup & trade advice</h2></div></div><div id="advice-engine"></div></article><article class="surface form-surface"><div id="opponent-roster-editor"></div></article>`);const style=document.createElement('style');style.textContent=`.advice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.advice-card,.weekly-roster-panel{border:1px solid var(--border,#d9dee8);border-radius:14px;padding:16px}.advice-card>span{font-size:11px;font-weight:800;letter-spacing:.08em}.advice-card h3{margin:6px 0 8px}.advice-metrics{display:flex;gap:10px;margin:14px 0}.advice-metrics b{font-size:22px}.advice-metrics small,.roster-edit-row small{display:block;font-size:10px;font-weight:500}.trade-row,.roster-edit-row{display:flex;justify-content:space-between;align-items:center;gap:12px;border-top:1px solid var(--border,#d9dee8);padding:9px 0}.weekly-roster-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.current-roster{max-height:390px;overflow:auto;margin-top:12px}.roster-add{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:12px}.roster-add select{min-width:0}@media(max-width:800px){.advice-grid,.weekly-roster-grid{grid-template-columns:1fr}}`;document.head.appendChild(style)}
installAdviceUI();renderOpponentRosterEditor();renderAdvice();
const adviceBaseRenderLeagueTeams=renderLeagueTeams;renderLeagueTeams=function(){adviceBaseRenderLeagueTeams();renderOpponentRosterEditor();renderAdvice()};
const adviceBaseDraftPlayer=draftPlayer;draftPlayer=function(id){const info=teamForOverall(currentOverallPick());adviceBaseDraftPlayer(id);syncDraftRosters();saveState()};
const adviceBaseUndoPick=undoPick;undoPick=function(){adviceBaseUndoPick();syncDraftRosters();saveState()};
