const DEFAULT_LEAGUE_TEAMS_14 = [
  'Kimchi Eaters', 'Commissioner…', "G’s Spots", 'I Love Hockey!', 'Touchdown & …',
  'Team Reynolds', 'Muscles By Mel', 'Mayor of OTF', "Jesse’s No…", 'My Guy',
  'Jake Only We…', 'HIIT Happens', 'Ihatefantasy…', 'Chorizos'
];
function isGenericLeagueName(name,slot){const v=String(name||'').trim();return !v||v===`Team ${slot}`||v===`Team ${slot} name`||(slot===Number(state.settings.draftSlot)&&v==='My Team')}
function ensureLeagueData(){const count=Math.max(2,Number(state.settings.teams)||14);if(!Array.isArray(state.leagueTeams))state.leagueTeams=[];const existing=new Map(state.leagueTeams.map(t=>[Number(t.slot),t]));let migrated=false;state.leagueTeams=Array.from({length:count},(_,i)=>{const slot=i+1,old=existing.get(slot)||{},preset=count===14?DEFAULT_LEAGUE_TEAMS_14[i]:'';const name=(preset&&isGenericLeagueName(old.name,slot))?preset:(old.name||preset||`Team ${slot}`);if(name!==old.name)migrated=true;return{...old,slot,name}});if(!state.matchups||typeof state.matchups!=='object')state.matchups={};const mine=state.leagueTeams.find(t=>t.slot===Number(state.settings.draftSlot));if(mine&&isGenericLeagueName(state.settings.teamName,state.settings.draftSlot)){state.settings.teamName=mine.name;migrated=true}if(migrated)saveState()}
function leagueTeamName(slot){ensureLeagueData();return state.leagueTeams.find(t=>t.slot===Number(slot))?.name||`Team ${slot}`}
function installLeagueUI(){ensureLeagueData();const backupNav=document.querySelector('.nav-item[data-tab="backup"]');if(backupNav&&!document.querySelector('[data-tab="league"]'))backupNav.insertAdjacentHTML('beforebegin','<button class="nav-item" data-tab="league">Teams & Matchups</button>');const backupView=document.getElementById('view-backup');if(backupView&&!document.getElementById('view-league'))backupView.insertAdjacentHTML('beforebegin',`<section class="view" id="view-league"><div class="page-head compact-head"><div><div class="eyebrow">LEAGUE</div><h1>Teams & weekly matchups</h1><p class="page-copy">Name every team in your league, identify opponents and save each week's matchup for lineup, waiver and trade advice.</p></div></div><article class="surface form-surface"><div class="surface-head no-pad"><div><span class="section-label">LEAGUE TEAMS</span><h2>Team names by draft slot</h2></div><button class="btn primary small" id="save-team-names">Save team names</button></div><p class="helper">The 14 names from your Yahoo draft order are prefilled when the league has 14 teams. Edit the shortened names to their full Yahoo names.</p><div class="league-teams-grid" id="league-teams-grid"></div></article><article class="surface form-surface matchup-surface"><div class="surface-head no-pad"><div><span class="section-label">WEEKLY OPPONENT</span><h2>Select matchup</h2></div></div><div class="matchup-controls"><label>Week<input id="matchup-week" type="number" min="1" max="18" value="1"></label><label>Opponent<select id="matchup-opponent"></select></label><button class="btn primary" id="save-matchup">Save matchup</button></div><div id="matchup-summary"></div></article></section>`);const style=document.createElement('style');style.textContent=`.league-teams-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px;margin-top:18px}.team-name-card{display:flex;flex-direction:column;gap:7px;padding:12px;border:1px solid var(--border,#d9dee8);border-radius:12px}.team-name-card.mine{outline:2px solid var(--accent,#5b5bd6)}.team-name-card span{font-size:11px;font-weight:800;letter-spacing:.06em}.team-name-card input{width:100%}.matchup-controls{display:grid;grid-template-columns:120px minmax(220px,1fr) auto;gap:12px;align-items:end;margin:18px 0}.matchup-card{padding:18px;border:1px solid var(--border,#d9dee8);border-radius:14px}.matchup-card span{display:block;font-size:11px;font-weight:800;letter-spacing:.08em}.matchup-card strong{display:block;font-size:22px;margin:7px 0}.matchup-card em{font-style:normal;font-weight:500;opacity:.55;margin:0 8px}@media(max-width:700px){.matchup-controls{grid-template-columns:1fr}}`;document.head.appendChild(style)}
function renderLeagueTeams(){ensureLeagueData();const grid=document.getElementById('league-teams-grid');if(!grid)return;grid.innerHTML=state.leagueTeams.map(team=>`<label class="team-name-card ${team.slot===Number(state.settings.draftSlot)?'mine':''}"><span>Draft slot ${team.slot}${team.slot===Number(state.settings.draftSlot)?' · MY TEAM':''}</span><input data-team-slot="${team.slot}" value="${esc(team.name)}"></label>`).join('');const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||1)),select=document.getElementById('matchup-opponent');if(select){select.innerHTML='<option value="">Select opponent</option>'+state.leagueTeams.filter(t=>t.slot!==Number(state.settings.draftSlot)).map(t=>`<option value="${t.slot}">${esc(t.name)} · Slot ${t.slot}</option>`).join('');select.value=state.matchups[String(week)]||''}renderMatchupSummary()}
function renderMatchupSummary(){const box=document.getElementById('matchup-summary');if(!box)return;const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||1)),opponent=Number(state.matchups[String(week)]||0);box.innerHTML=opponent?`<div class="matchup-card"><span>WEEK ${week}</span><strong>${esc(leagueTeamName(state.settings.draftSlot))} <em>vs</em> ${esc(leagueTeamName(opponent))}</strong><p>Use this opponent for matchup-specific lineup, waiver and trade decisions.</p></div>`:`<div class="empty-state compact">Choose your Week ${week} opponent to anchor matchup-specific advice.</div>`}
function saveLeagueTeams(){ensureLeagueData();document.querySelectorAll('[data-team-slot]').forEach(input=>{const t=state.leagueTeams.find(x=>x.slot===Number(input.dataset.teamSlot));if(t)t.name=input.value.trim()||`Team ${t.slot}`});const mine=state.leagueTeams.find(t=>t.slot===Number(state.settings.draftSlot));if(mine)state.settings.teamName=mine.name;saveState();populateSettings();renderAll();renderLeagueTeams();toast('League team names saved')}
function saveWeeklyMatchup(){ensureLeagueData();const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week').value)||1)),opponent=Number(document.getElementById('matchup-opponent').value||0);if(opponent)state.matchups[String(week)]=opponent;else delete state.matchups[String(week)];saveState();renderMatchupSummary();toast(opponent?`Week ${week} matchup saved`:`Week ${week} matchup cleared`)}
function bindLeagueControls(){document.querySelector('.nav-item[data-tab="league"]')?.addEventListener('click',()=>{switchTab('league');renderLeagueTeams()});document.getElementById('save-team-names')?.addEventListener('click',saveLeagueTeams);document.getElementById('save-matchup')?.addEventListener('click',saveWeeklyMatchup);document.getElementById('matchup-week')?.addEventListener('change',renderLeagueTeams)}
installLeagueUI();bindLeagueControls();renderLeagueTeams();
const baseRenderDraft=renderDraft;renderDraft=function(){baseRenderDraft();ensureLeagueData();const info=teamForOverall(currentOverallPick());if(info.round<=state.settings.rounds)document.getElementById('draft-team-title').textContent=`${leagueTeamName(info.teamSlot)} is on the clock`;document.querySelectorAll('#draft-board .board-cell.header:not(.round-label)').forEach((el,i)=>{el.textContent=leagueTeamName(i+1)})};
const baseRenderPlayers=renderPlayers;renderPlayers=function(){baseRenderPlayers();document.querySelectorAll('#players-body .status-text.drafted').forEach(el=>{const m=el.textContent.match(/^Team (\d+) ·/);if(m)el.textContent=el.textContent.replace(`Team ${m[1]}`,leagueTeamName(Number(m[1])))})};
const baseRenderAll=renderAll;renderAll=function(){baseRenderAll();renderLeagueTeams()};
