// AI analysis layer. Firebase Hosting rewrites this same-origin endpoint to the secure Cloud Function.
const AI_ENDPOINT='/api/ai-advice';
function aiEndpoint(){return AI_ENDPOINT}
async function authorizedJsonHeaders(){const headers={'Content-Type':'application/json'};if(typeof window.fmAuthToken==='function'){const token=await window.fmAuthToken();if(token)headers.Authorization=`Bearer ${token}`}return headers}
function compactPlayer(p,targetPick){const base={name:p.name,pos:primaryPos(p),team:p.team||'',rank:num(p.rank),adp:num(p.adp),projection:num(p.projection),status:p.status||''};const ds=typeof defenseScore==='function'?defenseScore(p):null;if(ds)base.defense={score:ds.score,source:ds.source,seasonBlend:ds.seasonBlend,inputsPresent:ds.inputsPresent,evidence:ds.evidence};if(typeof draftValueContext==='function'&&targetPick)return{...base,draftValue:draftValueContext(p,targetPick)};return base}
function aiDraftContext(){ensureLeagueData?.();const overall=currentOverallPick(),info=teamForOverall(overall),guard=typeof draftGuardContext==='function'?draftGuardContext():null,draftRoster=slot=>typeof draftRosterForSlot==='function'?draftRosterForSlot(slot):(state.picks||[]).filter(x=>Number(x.teamSlot)===Number(slot)).map(x=>getPlayer(x.playerId)).filter(Boolean);let rawAvailable=state.players.filter(p=>!state.picks.some(x=>x.playerId===p.id)).sort((a,b)=>recommendationScore(b,overall)-recommendationScore(a,overall)).slice(0,70);const available=typeof guardedDraftCandidates==='function'?guardedDraftCandidates(rawAvailable).slice(0,35):rawAvailable.slice(0,35);return{mode:'draft',league:{name:state.settings.leagueName,teams:state.settings.teams,scoring:state.settings.scoring,roster:state.settings.roster,draftSlot:state.settings.draftSlot},pick:{overall,round:info.round,teamSlot:info.teamSlot,teamName:typeof leagueTeamName==='function'?leagueTeamName(info.teamSlot):`Team ${info.teamSlot}`},draftState:{sourceOfTruth:'recorded draft picks only',recordedPicks:(state.picks||[]).length,note:'Roster membership in this draft context is derived only from the current draft pick log. Ignore any historical season roster state.'},strategy:{rankingModel:'overall ECR + ADP + value over replacement + league positional scarcity + roster construction + blended D/ST defense score',rule:'Do not confuse positional rank with overall draft value. In 1-QB leagues, strongly avoid a second QB after QB is filled unless roster needs are complete. Likewise avoid a second TE while RB/WR/FLEX starter needs remain. K/DST should normally wait until late rounds unless the completion guard requires them. For D/ST, use the supplied defense score and its prior/current season blend to rank defenses against one another; never invent defensive stats that are absent.'},rosterCompletion:guard,myRoster:draftRoster(state.settings.draftSlot).map(p=>compactPlayer(p,overall)),allTeamRosters:state.leagueTeams?.map(t=>({team:t.name,slot:t.slot,players:draftRoster(t.slot).map(p=>compactPlayer(p,overall))}))||[],available:available.map(p=>compactPlayer(p,overall))}}
function compactWeeklyPlayer(p,week){
  const w=typeof weeklyPlayerContext==='function'?weeklyPlayerContext(p,week):null;
  return{
    name:p?.name||w?.name||'',pos:typeof primaryPos==='function'?primaryPos(p):(w?.pos||''),team:p?.team||w?.team||'',status:p?.status||w?.status||'',
    rank:num(p?.rank),adp:num(p?.adp),seasonProjection:num(p?.projection),
    weekProjection:num(w?.baseWeeklyProjection),adjustedWeekProjection:num(w?.adjustedWeeklyProjection),projectionSource:w?.projectionSource||'',realWeeklyProjection:!!w?.realWeeklyProjection,
    nflOpponent:w?.nflOpponent||null,home:w?.home??null,bye:w?.bye??false,gameTime:w?.gameTime||null,matchupFactor:num(w?.matchupFactor)
  };
}
function compactNflWeek(week){
  const raw=state.nflWeeks?.[String(week)]||null;if(!raw)return null;
  return{season:raw.season||state.settings?.season||null,week:Number(raw.week)||Number(week),source:raw.source||'',fetchedAt:raw.fetchedAt||'',projectionStatus:raw.projectionStatus?{available:!!raw.projectionStatus.available,provider:raw.projectionStatus.provider||'',count:Number(raw.projectionStatus.count)||0,matchedPlayers:Number(raw.projectionStatus.matchedPlayers)||0,scoring:raw.projectionStatus.scoring||'',fetchedAt:raw.projectionStatus.fetchedAt||'',error:raw.projectionStatus.error||''}:null,games:(raw.games||[]).map(g=>({home:g.home,away:g.away,date:g.date||'',status:g.status||'',completed:!!g.completed,venue:g.venue||'',indoor:g.indoor??null,neutralSite:!!g.neutralSite,weather:g.weather||'',temperature:g.temperature??null,wind:g.wind??null,overUnder:g.overUnder??null,spread:g.spread??null,oddsDetails:g.oddsDetails||''}))};
}
function aiWeeklyContext(){
  const week=Math.max(1,Math.min(18,Number(document.getElementById('matchup-week')?.value)||Number(state.currentWeek)||1)),a=typeof matchupAnalysis==='function'?matchupAnalysis(week):null;if(!a?.opponent)return null;
  const sim=typeof simulateWeeklyMatchup==='function'?simulateWeeklyMatchup(week,2500):null,ctx=p=>compactWeeklyPlayer(p,week);
  const allLeagueRosters=(state.leagueTeams||[]).map(t=>({team:t.name,slot:t.slot,players:(typeof rosterForSlot==='function'?rosterForSlot(t.slot):[]).map(ctx)}));
  const tradeIdeas=typeof tradeCandidates==='function'?tradeCandidates(a.opponent).slice(0,8).map(x=>({target:ctx(x.target),offer:x.give?ctx(x.give):null})):[];
  const simulation=sim?{runs:sim.runs,myMean:Number(sim.myMean.toFixed(2)),opponentMean:Number(sim.opponentMean.toFixed(2)),projectedEdge:Number((sim.myMean-sim.opponentMean).toFixed(2)),winProbability:Number(sim.winProbability.toFixed(4)),method:sim.method||'Monte Carlo over best legal starting lineups',varianceModel:sim.varianceModel||'',starterCountMine:sim.starterCountMine||null,starterCountOpponent:sim.starterCountOpponent||null}:null;
  return{mode:'weekly',week,league:{name:state.settings.leagueName,teams:state.settings.teams,scoring:state.settings.scoring,roster:state.settings.roster},matchup:{myTeam:leagueTeamName(state.settings.draftSlot),opponent:leagueTeamName(a.opponent),simulation},nflWeek:compactNflWeek(week),myRoster:a.mine.map(ctx),opponentRoster:a.theirs.map(ctx),allLeagueRosters,deterministicTradeIdeas:tradeIdeas};
}
async function requestAiAdvice(mode){const out=document.getElementById(mode==='draft'?'ai-draft-output':'ai-weekly-output');if(!out)return;let context=mode==='draft'?aiDraftContext():aiWeeklyContext();if(!context){out.innerHTML='<div class="ai-note">Save a weekly matchup first.</div>';return}out.innerHTML=window.aiLoadingMarkup?window.aiLoadingMarkup(mode==='draft'?'Thinking through the draft board':'Thinking through your weekly matchup',mode==='draft'?'Weighing ECR, ADP, roster needs and scarcity.':'Reading lineup, opponent, projection and league roster context.'): '<div class="ai-note">Analyzing current league data...</div>';try{if(mode==='weekly'&&typeof loadNflWeek==='function'){await loadNflWeek(context.week);context=aiWeeklyContext()||context}const payload={task:mode,context},serialized=JSON.stringify(payload);if(serialized.length>150000&&mode==='weekly'){context.allLeagueRosters=context.allLeagueRosters.map(t=>({...t,players:t.players.map(p=>({name:p.name,pos:p.pos,team:p.team,status:p.status,rank:p.rank,adjustedWeekProjection:p.adjustedWeekProjection,realWeeklyProjection:p.realWeeklyProjection,nflOpponent:p.nflOpponent,home:p.home}))}));}const res=await fetch(aiEndpoint(),{method:'POST',headers:await authorizedJsonHeaders(),body:JSON.stringify({task:mode,context})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`AI service returned ${res.status}`);const text=String(data.advice||'').trim();if(!text)throw new Error('AI service returned no advice');out.innerHTML=`<div class="ai-response">${esc(text).replaceAll('\n','<br>')}</div>`;if(mode==='draft'&&typeof addAiDraftAction==='function')addAiDraftAction(text);if(mode==='weekly'&&typeof renderNflIntel==='function')renderNflIntel();return text}catch(e){out.innerHTML=`<div class="ai-note"><strong>AI analysis unavailable.</strong><br>${esc(e.message)}<br>The projection/ECR/ADP engine remains active.</div>`;throw e}}
function installAiUI(){if(!document.getElementById('ai-style')){const s=document.createElement('style');s.id='ai-style';s.textContent='.ai-panel{margin-top:14px;padding:16px;border:1px solid var(--border,#d9dee8);border-radius:14px}.ai-panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.ai-panel h3{margin:4px 0}.ai-note{margin-top:12px;padding:14px;border:1px dashed var(--border,#d9dee8);border-radius:12px;opacity:.8}.ai-response{margin-top:12px;line-height:1.55}.ai-badge{font-size:10px;font-weight:800;letter-spacing:.08em}@media(max-width:700px){.ai-panel-head{align-items:stretch;flex-direction:column}}';document.head.appendChild(s)}const draftSurface=document.querySelector('#view-draft .draft-recommendations')||document.querySelector('#view-draft .surface');if(draftSurface&&!document.getElementById('ai-draft-output'))draftSurface.insertAdjacentHTML('beforeend','<div class="ai-panel"><div class="ai-panel-head"><div><span class="ai-badge">AI DRAFT ANALYST</span></div><button class="btn primary small" id="ask-ai-draft">Ask AI</button></div><div id="ai-draft-output" class="ai-note">AI combines overall ECR, ADP, value over replacement, league scarcity, roster construction and the live draft board.</div></div>');const advice=document.getElementById('advice-engine');if(advice&&!document.getElementById('ai-weekly-output'))advice.insertAdjacentHTML('afterend','<div class="ai-panel"><div class="ai-panel-head"><div><span class="ai-badge">AI FANTASY GM</span><h3>NFL matchup, lineup & trade strategy</h3></div><button class="btn primary small" id="ask-ai-weekly">Ask AI</button></div><div id="ai-weekly-output" class="ai-note">AI uses actual NFL opponents, matchup-adjusted projections, simulations and all league rosters.</div></div>');document.getElementById('ask-ai-draft')?.addEventListener('click',()=>requestAiAdvice('draft').catch(()=>{}));document.getElementById('ask-ai-weekly')?.addEventListener('click',()=>requestAiAdvice('weekly').catch(()=>{}))}
installAiUI();
